### ISSUE TITLE
Can I checkout source code from RTC Workspace?

### ISSUE THREAD

**Issue by OHerasym** [dixudx/rtcclient#104]
Hi all, 

How can  I checkout source code from RTC Workspace? I didn't found any examples.

Thanks!

**Comment by kevinhe2017** [comment]
If I understand correctly, you want to see the source code of RTC pages which is in xml format. The pages are like the regular web pages. So you can click View on top then select Source, or just do "Ctrl+U".

**Comment by OHerasym** [comment]
@kevinhe2017 , @dixudx , Thanks. Already resoved issue by using scmtool from Eclipse. 

but why not add this functionality to this library?(by using scmtool for example)  It will be very helpful for automatization. All you need in one lib.

**Comment by dixudx** [comment]
@OHerasym This may be a good feature IMO. Would you like to implement this? I don't have too much bandwidth for this.

Really appreciate.
