### ISSUE TITLE
Status 400 when trying to add comment to WorkItem with Jazz 6.0.4

### ISSUE THREAD

**Issue by Mershl** [dixudx/rtcclient#106]
Hi @dixudx,

I'm currently seeing the following error when trying to create comments to "some" Tasks. "Some" because it's working for some tasks and for others it's never working. I try to reproduce it.

Error output:
```
<oslc_cm:error xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/">
<oslc_cm:status>400</oslc_cm:status>
<oslc_cm:message>Not a comment identifier: oslc:comment</oslc_cm:message>
</oslc_cm:error>
```

**Comment by Mershl** [comment]
Found the culprit.

Posting a message including special characters like "&" will lead to a "client error 400 - Not a comment identifier: oslc:comment".

**Comment by dixudx** [comment]
> Posting a message including special characters like "&" will lead to a "client error 400

@Mershl For these special characters, you need to encode. Please refer to [https://www.w3schools.com/tags/ref_urlencode.asp](HTML URL Encoding Reference).

For example, `&` should be `%26` to avoid being recognized as normal `&` when making a request.
