### ISSUE TITLE
How to update a custom attribute value with Python "RTCClient"

### ISSUE THREAD

**Issue by GJor** [dixudx/rtcclient#118]
Team,
is there a way to update a custom defined (string) attribute in an existing workitem in the Python "RTCClient"? Somehow I cannot find how to do it..

**Comment by dixudx** [comment]
> is there a way to update a custom defined (string) attribute in an existing workitem in the Python "RTCClient"?

Now creating a workitem with custom defined attribute is supported. But updating an existing workitem is not supported yet.

xref #7

**Comment by dixudx** [comment]
dup of #7.

Close it. Move discussion to #7.
