### ISSUE TITLE
Version0.7.0 login-cookie missed ,repeat login 

### ISSUE THREAD

**Issue by hiro-icear** [dixudx/rtcclient#145]
I use EWM 7.0.2 (WASLIBERTY), but returned a response value  authfailed="Authrequired" 
main.py sourcecode
   myclient = RTCClient(options.host, options.user, options.password, ends_with_jazz=False)
client.py
        # authfailed
        authfailed = resp.headers.get("x-com-ibm-team-repository-web-auth-msg") <--"Authrequired"
        if authfailed == "authfailed":

I think this is the same as #136.

But version 0.6.0, it works fine.

**Comment by dixudx** [comment]
> But version 0.6.0, it works fine.

**Comment by hiro-icear** [comment]
Someday, we look forward to the day when the latest version can be used!
