### ISSUE TITLE
rtcclient ownedBy returns User ID and not email address

### ISSUE THREAD

**Issue by MartinBarkerPhilips** [dixudx/rtcclient#147]
I am using the Python package rtclcient (v0.6.0) to get info from work item.
Some of the properties I am querying from my RTC work item include:
```
returned_properties_list = [
    "rtc_cm:modifiedBy",
    "dc:modified",
    "rtc_cm:contextId",
    "dc:subject",
    "oslc_cm:priority",
    "dc:creator",
    "rtc_cm:due",
    "rtc_cm:estimate",
    "rtc_cm:correctedEstimate",
    "rtc_cm:timeSpent",
    "rtc_cm:startDate",
    "dc:created",
    "rtc_cm:resolvedBy",
    "rtc_cm:plannedFor",
    
    "rtc_cm:ownedBy",
]
```

When the query for these items finish and I examine the returned variables, I notice that the 'ownedBy' value is the user's id, not their email address.
[![enter image description here][1]][1]
If I look at the value of `raw_data['rtc_cm:ownedBy']['@rdf:resource']` it is a link which goes to that user's profile. 

On the profile I can see the same User ID which is being recieved as the 'ownedBy' value.
[![enter image description here][2]][2]
Also on the profile is the User's E-mail Address. This email address value is what I need, but I can't seem to find a way to query for this value using the rtcclient python package.

I've tried adding `"rtc_cm:emailAddress"` to my query properties but no luck,

**Can anyone help me get the ownedBy user email address for a RTC ticket using the rtcclient package? Thanks**

  [1]: https://i.stack.imgur.com/mhfdv.png
  [2]: https://i.stack.imgur.com/IbUk3.png

**Comment by dixudx** [comment]
@MartinBarkerPhilips You can refer all the returned properties with [this snippet](https://rtcclient.readthedocs.io/en/latest/quickstart.html#about-returned-properties).

> Can anyone help me get the ownedBy user email address for a RTC ticket using the rtcclient package? Thanks

You can check all the returned properties and find out whether there is a property contains the user email. Current RTCClient has returned all the properties that it can find. If not found, you may need other ways to get this value.

**Comment by MartinBarkerPhilips** [comment]
I can see an XML page with profile info ( user id / email ) for every user using this url:
`https://rtcus1.ta.company.com/ccm/oslc/users?oslc_cm.pageSize=50&_resultToken=_token&_startIndex=0`
If I know the userId of someone, like for example `320178017` , is there some way I could append that to my url, so I can see xml profile info for one specific user ? I thought something like this would work but it just redirects me back to an xml view of every user:
`https://rtcus1.ta.company.com/ccm/oslc/users?rtc_cm.userId=320178017`

I figure if I can access a user's profile data via url, I could probably make a get request to that url with authentication info in the header/body, then parse the result to retrieve the user email

**Comment by MartinBarkerPhilips** [comment]
I made my own function in client.pt : `def getUserEmail(self, user_id):`

**Comment by dixudx** [comment]
> I made my own function in client.py : `def getUserEmail(self, user_id):`

@MartinBarkerPhilips Would you please submit a PR on this? Thanks so much.
