### ISSUE TITLE
workItem.getChildren() taking forever and printing 'unable to handle' error messages

### ISSUE THREAD

**Issue by MartinBarkerPhilips** [dixudx/rtcclient#150]
Hello, I am trying to use the .getChildren() function in python to get the ID numbers for each child task linked to a parent epic. The code works, but I've experienced some incredibly long wait times for this function to complete when there are more then 3 child tasks. 
My python script will even throw some error messages (that dont interrupt the script) such as:
```
Unable to handle https://rtcus1.ta.company.com/ccm/oslc/workflows/_wO------w/states/com.ibm.team.apt.storyWorkflow/com.ibm.team.apt.story.verified

Unable to handle https://rtcus1.ta.company.com/ccm/oslc/enumerations/_S-----------/priority/priority.literal.l01

Unable to handle https://rtcus1.ta.compay.com/ccm/oslc/enumerations/_S--------/planned.status.enumeration/planned.status.enumeration.literal.l4

Unable to handle https://rtcus1.ta.company.com/ccm/oslc/workitems/_------/calm:affectedByDefect
```
I was wondering if there was a faster way to retrieve these child ticket ids? Since right now it returns a list of objects like so: `[<Workitem 174645>, <Workitem 180013>, <Workitem 162543>, <Workitem 162552>, <Workitem 174646>, <Workitem 170641>, <Workitem 188736>, <Workitem 163504>, <Workitem 184451>, <Workitem 172243>, <Workitem 191868>, <Workitem 167094>, <Workitem 164459>, <Workitem 165773>, <Workitem 202261>, <Workitem 184446>, <Workitem 147299>, <Workitem 162545>, <Workitem 162555>, <Workitem 189361>, <Workitem 156406>, <Workitem 162583>, <Workitem 173240>, <Workitem 162541>, <Workitem 162557>, <Workitem 184449>]` Is there any way I could return jus the id numbers? And are these 'unable to x' error messages something to be concerned about? What do they mean

**Comment by dixudx** [comment]
@MartinBarkerPhilips What's your rtcclient version?

In #148, multiprocessing was introduces to help speed up the queries. You can take a try.

**Comment by dixudx** [comment]
> Is there any way I could return jus the id numbers?

You can create a query for this. Please refer [this doc](https://rtcclient.readthedocs.io/en/latest/quickstart.html#query-workitems) for details.

But for querying children workitems, I don't find a good way to make up a query string. I don't know whether newer RTC has provided newer APIs for this.

**Comment by MartinBarkerPhilips** [comment]
@dixudx I am currently using v0.6.0 with a slight code modification to prevent an error "ssl key too short" that I was facing with my companies (older) version of RTC

In a previous issue you mentioned:
```
v0.7.0 had introduced a change on authentication, refer to https://github.com/dixudx/rtcclient/pull/133 for details, which may be not compatible with older Rational Team Concert. From your issue, it seems to be true. Sorry for this.

My suggestion is just sticking with older rtcclient version, such as pip install rtcclient==0.6.0.
```
Which is why I've been sticking to v0.6.0, and will probably need to continue using v0.6.0.

Maybe I can take the 'Pull Request' file changes in your #148 link, and add them into my local code

**Comment by MartinBarkerPhilips** [comment]
If I clone this repo, install it locally, and add this code before requests.get( in base.py (to fix ssl key too short error)
```
        requests.packages.urllib3.disable_warnings()
        requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += ':HIGH:!DH:!aNULL'
        try:
            requests.packages.urllib3.contrib.pyopenssl.util.ssl_.DEFAULT_CIPHERS += ':HIGH:!DH:!aNULL'
        except AttributeError:
            # no pyopenssl support used / needed / available
            pass
```
I then start python shell and run these commands to loginto my rtc account:
```
from rtcclient.utils import setup_basic_logging
from rtcclient import RTCClient
setup_basic_logging()
myclient = RTCClient("https://rtcus1.ta.company.com/ccm", "username", "password", ends_with_jazz=False)
myclient.getWorkitem("168082")
```
But it results in an error saying:
```
Traceback (most recent call last):
  File "c:\users\320178017\documents\repos\rtc-ads-import\myLocalFolderRTCCLIENT\rtcclient\client.py", line 1018, in getWorkitem
    raw_data = xmltodict.parse(resp.content)
  File "C:\Users\320178017\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 17, column 77

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\320178017\documents\repos\rtc-ads-import\myLocalFolderRTCCLIENT\rtcclient\client.py", line 1031, in getWorkitem
    raise exception.NotFound("Not found <Workitem %s>" % workitem_id)
rtcclient.exception.NotFound: Not found <Workitem 168082>
```
so im going to investigate how I can make this current version of rtcclient (v0.8.0) work with my companies older version of rtc which previously only worked with 0.6.0. 
Not sure where this auth change lies, once I find it I could reverse it

**Comment by MartinBarkerPhilips** [comment]
I believe I came up with a temporary fix by making my own custom function rtcclient.getChildIds(rtc_parent_id) which returns a list of only the child ids in a ticket

**Comment by MartinBarkerPhilips** [comment]
I was able to get it working I think, just had to solve each cherry pick commit issue one at a time.
