### ISSUE TITLE
Can't find projectarea

### ISSUE THREAD

**Issue by MartinBarkerPhilips** [dixudx/rtcclient#165]
Hello, I am trying to use rtcclient v6.0 to read work items from an RTC project which has special characters and spaces in the project title. Due to this I have been having trouble getting authentication to work with my project.

My rtc dashboard url looks like this:
```
https://rtcemea1.company.com:9443/ccm/web/projects/(HC)%20CT%20AMI%20FRU#action=com.ibm.team.dashboard.viewDashboard
```

Where in the URL the project name looks like `(HC)%20CT%20AMI%20FRU` and URL decodes to `(HC) CT AMI FRU`

if I try to use these vars for my RTCCLIENT auth:
```
RTC_URL = "https://rtcemea1.company.com:9443/ccm"   
RTC_projectarea_name = '(HC) CT AMI FRU' 
```

It will raise an exception `No ProjectArea named (HC) CT AMI FRU` inside the getProjectArea function:

```
    def getProjectArea(self, projectarea_name, archived=False,
                       returned_properties=None):
        """Get :class:`rtcclient.project_area.ProjectArea` object by its name

        :param projectarea_name: the project area name
        :param archived: (default is False) whether the project area
            is archived
        :param returned_properties: the returned properties that you want.
            Refer to :class:`rtcclient.client.RTCClient` for more explanations
        :return: the :class:`rtcclient.project_area.ProjectArea` object
        :rtype: rtcclient.project_area.ProjectArea
        """

        if not isinstance(projectarea_name,
                          six.string_types) or not projectarea_name:
            excp_msg = "Please specify a valid ProjectArea name"
            self.log.error(excp_msg)
            raise exception.BadValue(excp_msg)
        self.log.debug("Try to get <ProjectArea %s>", projectarea_name)
        rp = returned_properties
        proj_areas = self._getProjectAreas(archived=archived,
                                           returned_properties=rp,
                                           projectarea_name=projectarea_name)

        if proj_areas is not None:
            proj_area = proj_areas[0]
            self.log.info("Find <ProjectArea %s>", proj_area)
            return proj_area

        self.log.error("No ProjectArea named %s", projectarea_name)
        raise exception.NotFound("No ProjectArea named %s" % projectarea_name)
```

This same error occurs if I try to use the url encoded string from the URL:
```
RTC_projectarea_name = "(HC)%20CT%20AMI%20FRU" 
```

is there any way I could view all my project areas to see what the name of the project is? Im concerned that because my RTC project name has spaces and parenthesis  in it, that it is causing issues trying to connect that I've never faced before.

**Comment by MartinBarkerPhilips** [comment]
update, I ran ` myclient.getProjectAreas(archived=False, returned_properties="dc:title,dc:identifier")` and this project did not show up, so I think my rtc project area is not setup correctly, or missing an access requirement which this package needs

**Comment by dixudx** [comment]
> is there any way I could view all my project areas to see what the name of the project is?

I don't know whether the projectarea `(HC) CT AMI FRU` will be encoded or not.

I'd suggest listing all the project areas and pick it out with iteration.

**Comment by MartinBarkerPhilips** [comment]
> > is there any way I could view all my project areas to see what the name of the project is?
> 
> I don't know whether the projectarea `(HC) CT AMI FRU` will be encoded or not.
> 
> I'd suggest listing all the project areas and pick it out with iteration.

I listed all the project areas and mine was missing from the list, like rtcclient cant find it as a project area for some reason.

is there some setting in my rtc project config that needs to be changed in order to allow for the python api to be able to find my project? such as changing the access control setting for my rtc project to 'everyone' instead of 'team members' ?

or maybe the username/password for rtc im using dont have correct permission?

**Comment by dixudx** [comment]
> I listed all the project areas and mine was missing from the list, like rtcclient cant find it as a project area for some reason.
>
>is there some setting in my rtc project config that needs to be changed in order to allow for the python api to be able to find my project? 

@MartinBarkerPhilips As long as you can get a list of project areas, that means it is okay with the config settings.

I am wondering whether that project area is marked as **Archived**. Please have a try on it.

```python
myclient.getProjectAreas(archived=True)
```

> such as changing the access control setting for my rtc project to 'everyone' instead of 'team members' ?
>
> or maybe the username/password for rtc im using dont have correct permission?

Are you using a special account for the client?

If you can view that project area from web browser, then the client can access as well.

**Comment by MartinBarkerPhilips** [comment]
I made a simple script to print all project areas:
```
from rtcclient.utils import setup_basic_logging
from rtcclient import RTCClient
setup_basic_logging()

myclient = RTCClient("https://rtcemea1.philips.com:9443/ccm", "username", "password", ends_with_jazz=False)
areas = myclient.getProjectAreas(archived=True, returned_properties="dc:title,dc:identifier")
for a in areas:
    print(a.title)
```
It prints out these:
```
(HC) IGTS MoS
(HC) IGTS Externals
(HC) IGTS SmartSuite FactoryTooling
(HC) IGTS FSFW
(HC) iXR iEngineCore
(HC) IGTS TAF Scripting
(HC) IGTS Tools
(HC) IGTS SmartSuite TestTooling
(HC) iXR SmartSuiteShared
```
But the project I need, `(HC) CT AMI FRU` is not included.

If i run the code with archived=false its the same output
```
(HC) IGTS MoS
(HC) IGTS Externals
(HC) IGTS SmartSuite FactoryTooling
(HC) IGTS FSFW
(HC) iXR iEngineCore
(HC) IGTS TAF Scripting
(HC) IGTS Tools
(HC) IGTS SmartSuite TestTooling
(HC) iXR SmartSuiteShared
``` 

I can see the project I want under 'my projects' online with the same username/password I used in my code
![image](https://user-images.githubusercontent.com/99444148/177379049-6315de10-b9cd-46a7-ac16-e0a1a9a84f4e.png)

Under the 'all other projects' tab i see alot of projects, including the ones my script printed out
![image](https://user-images.githubusercontent.com/99444148/177379202-bd03e760-3ea4-4807-8d01-ca6998760c59.png)

under the archived project tab there are a couple projects, none of which are the one i am trying to get: `(HC) CT AMI FRU`

**Comment by MartinBarkerPhilips** [comment]
I appreciate your help by the way thank you @dixudx

**Comment by dixudx** [comment]
> Under the 'all other projects' tab i see alot of projects, including the ones my script printed out

This seems to be a new category for project areas. We may need to add a new parameter to fetch project areas of this category.

@MartinBarkerPhilips Would you please inspect this web page, and refresh the page to see the network requests. I think we could get some clues on `All the other projects`.

**Comment by MartinBarkerPhilips** [comment]
Here is some insight on the network connections, there are no new connections when clicking the 'all other projects' tab. only when i refresh the page, which default goes to 'my projects'
![image](https://user-images.githubusercontent.com/99444148/178367388-797b7f86-cfc1-48c7-919f-f568a1044f23.png)

im talking with people in my org about a potential fix, my script is unable to connect with any project area under a certain group org so were going to try and add admin auth for me there

**Comment by dixudx** [comment]
I saw there was a request on `allProjectsAreas`. Would you please take a look on the response data and search the desired project areas that were missing.

![image](https://user-images.githubusercontent.com/5449021/179193260-ea78950c-6e08-4ed7-9f48-9d7a645622e3.png)

I guess the APIs may get changed.

**Comment by MartinBarkerPhilips** [comment]
If I click the 'allProjectAreas' in network tab, I can get a URL which I can go to

![image](https://user-images.githubusercontent.com/99444148/179239696-fd5de8cb-69e6-4cbf-b03e-69f2f5631349.png)

the url leads to an xml file with 29 instances of `xsi:type="rest:ProjectAreaDTO"` 
![image](https://user-images.githubusercontent.com/99444148/179240077-3d5a1867-4549-445f-88e1-7a9d6d0cc47d.png)

This is way more then when I run my script:
```
myclient = RTCClient("https://companyurl.com:9443/ccm", "username", "pword", ends_with_jazz=False)
areas = myclient.getProjectAreas()
``` 
and only returns these results:
```
(HC) IGTS MoS
(HC) IGTS Externals
(HC) IGTS SmartSuite FactoryTooling
(HC) IGTS FSFW
(HC) iXR iEngineCore
(HC) IGTS TAF Scripting
(HC) IGTS Tools
(HC) IGTS SmartSuite TestTooling
(HC) iXR SmartSuiteShared
```

Here is the URL xml value element for `(HC) IGTS Tools`, which appears above, and is a project area my script can find fine
```
<values xsi:type="rest:ProjectAreaDTO">
<itemId>abcdabcd</itemId>
<stateId>xyzxyzxz=yz</stateId>
<name>(HC) IGTS Tools</name>
<archived>false</archived>
<initialized>true</initialized>
<accessTime>2022-07-15T14:03:24.501Z</accessTime>
<myProjectArea>false</myProjectArea>
<description/>
<summary>(HC) IGTS Tools</summary>
<locale>en_US</locale>
<publicVisible>true</publicVisible>
<memberVisible>false</memberVisible>
<specificUserVisible>false</specificUserVisible>
<internalIsProcessProvider>false</internalIsProcessProvider>
<webUrl>https://companyurl:9443/ccm/web/projects/%28HC%29%20IGTS%20Tools</webUrl>
</values>
``` 

And here is the url xml element value for project area `(HC) CT AMI FRU`, which my script can not find currently
``` 
<values xsi:type="rest:ProjectAreaDTO">
<itemId>abcabcitem id</itemId>
<stateId>xyzxyzid</stateId>
<name>(HC) CT AMI FRU</name>
<archived>false</archived>
<initialized>true</initialized>
<accessTime>2022-07-15T14:03:24.485Z</accessTime>
<myProjectArea>true</myProjectArea>
<description/>
<summary>(HC) CT/AMI FRU</summary>
<locale>en_US</locale>
<publicVisible>false</publicVisible>
<memberVisible>true</memberVisible>
<specificUserVisible>false</specificUserVisible>
<internalIsProcessProvider>false</internalIsProcessProvider>
<webUrl>https://company url.com:9443/ccm/web/projects/%28HC%29%20CT%20AMI%20FRU</webUrl>
</values>
```

i am using version 0.6 of rtcclient since my company uses an older version of rtc, these above xml results are what appear in my web browser, i wonder if the findings can be replicated in my rtcclient package?

**Comment by MartinBarkerPhilips** [comment]
I checked the v0.6 code in client.py and followed what happens when i call `getProjectAreas`, found that it seems to be calling
```
        print('running request for url: ', resource_url)
        resp = self.get(resource_url,
                        verify=False,
                        proxies=self.proxies,
                        headers=self.headers)
```
inside
```
def _get_paged_resources
```
only once, and in my case its the very end, so its only finding the last 10 for some reason 
```
running request for url:  https://company.com:9443/ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0
```

**Comment by MartinBarkerPhilips** [comment]
I was able to implement a temporary fix by changing page_size="100" in this function (originally it was 10) but ill have to fix the _get_paged_resources pagination 

```
    def _getProjectAreas(self, archived=False, returned_properties=None,
                         projectarea_name=None, projectarea_id=None):
        rp = returned_properties

        filter_rule = None
        if projectarea_name is not None:
            fpaname_rule = ("dc:title", None, projectarea_name)
            filter_rule = self._add_filter_rule(filter_rule, fpaname_rule)

        if projectarea_id is not None:
            paid_url = "/".join([self.url, "oslc/projectareas",
                                 projectarea_id])
            fpaid_rule = ("@rdf:resource", None, paid_url)
            filter_rule = self._add_filter_rule(filter_rule, fpaid_rule)

        return self._get_paged_resources("ProjectArea",

                                         page_size="100",

                                         archived=archived,
                                         returned_properties=rp,
                                         filter_rule=filter_rule)
```

**Comment by MartinBarkerPhilips** [comment]
I think i came up with a fix for the _get_paged_resources function, by changing this section:

```
            # iterate all the entries
            with Pool() as p:
                resources_list_new = list(
                    filter(
                        None,
                        p.starmap(self._handle_resource_entry,
                                  [(resource_name, entry, pa_url, archived,
                                    filter_rule) for entry in entries])))
                resources_list = resources_list + resources_list_new
```
So that elements would get concatenated correctly

**Comment by MartinBarkerPhilips** [comment]
they werent getting concatenated correctly, so the `page_size` var number of results in resources_list would keep getting overwritten again and again, untill it would finally return the last `page_size` number of results only
