### ISSUE TITLE
xmltodict starts using dict instead of OrderedDict

### ISSUE THREAD

**Issue by dixudx** [dixudx/rtcclient#168]
From the [Python 3.7 changelog](https://docs.python.org/3.7/whatsnew/3.7.html):

> the insertion-order preservation nature of [dict](https://docs.python.org/3.7/library/stdtypes.html#typesmapping) objects [has been declared](https://mail.python.org/pipermail/python-dev/2017-December/151283.html) to be an official part of the Python language spec.

`xmltodict` starts using `dict` instead of `OrderedDict` from 0.13.0.

Currently in rtcclient, `OrderedDict` is still used to parse items from `xmltodict`. And we pinned `xmltodict<=0.12.0` in `requirements.txt` for now.

**Comment by gpongelli** [comment]
see PR https://github.com/dixudx/rtcclient/pull/178

**Comment by dixudx** [comment]
Wow, I did record an issue for this. I totally forget it.

**Comment by dixudx** [comment]
Close with PR #178
