### ISSUE TITLE
Add attachment fail because of KeyError : 'files'

### ISSUE THREAD

**Issue by LiangJunyi-010** [dixudx/rtcclient#173]
Hi dixudu,
After i create a new workitem, i try to add some attachments to it.
i use 
```
x = myclient.getWorkitem('1005083')
x.addAttachment(file path)
```

It will show KeyError: 'files'
It is because of the line in _workitem.py_
```
attachment_info = json_body["files"][0]
```
I try to print the json_body, it shows
`{'error':"CRJAZ6053E To complete the 'Save Work Item' task, you need these permissions: 'You don't have permission to perform the following actions:\n Add an attachment (modify/references/attachment/add)'"}`
I am not sure why the json_body looks like this and not know how to solve it.

Looking forward to your reply!
Thanks

**Comment by LiangJunyi-010** [comment]
Thanks for you reply,
Because currently i can manually add attachment but can not use python script.
I am not sure if my account did not have permission why it works for manually.

**Comment by dixudx** [comment]
> Thanks for you reply, Because currently i can manually add attachment but can not use python script. I am not sure if my account did not have permission why it works for manually.

Maybe the permissions are different for UI operations. Please try with other accounts that have enough permissions and see what happens.

**Comment by LiangJunyi-010** [comment]
Yes it works after i changed to another account. 
Thanks very much!

**Comment by dixudx** [comment]
Solved. Close it.
