### ISSUE TITLE
Suggestion: package version numbering

### ISSUE THREAD

**Issue by gpongelli** [dixudx/rtcclient#176]
Hi,
This is just a suggestion after some use, installing the package on project with poetry.

to avoid people upgrades the package to newer and not working version (e.g upgrading 0.6.0 -> 0.7.0 breaks mine), it’s better to use different major number for different RTC server, following semantic versioning.

I mean something like 
- 1.0.0 for the actual 0.6.0
- 2.0.0 for the actual 0.7.0 
- 3.0.0 for the actual 0.8.0
- And so on

in this way, if I’m on 1.0.0, I know that 2.0.0 can generally break something (and effectively it does, 0.7.0 does not work for me but 0.6.0 does).

furthermore you can add same feature (like handle an api endpoint) on all versions incrementing the “minor” number (without being crazy on specify which version works for which server).

so your numbering scheme become <server auth>.<feature>.<patch> , and using recent dependency tools like poetry (and probably also flit and setuptools), it will never suggest to upgrade 1.x to 2.x if this package is marked as “^1.0”.

regards.

**Comment by dixudx** [comment]
> installing the package on project with poetry.

This sounds good good to me. Also I notice that `poetry` could bring us great benefit. Would you like to work on this?

> I mean something like
>
>    1.0.0 for the actual 0.6.0
>    2.0.0 for the actual 0.7.0
>    3.0.0 for the actual 0.8.0
>    And so on
>
> in this way, if I’m on 1.0.0, I know that 2.0.0 can generally break something (and effectively it does, 0.7.0 does not work for me but 0.6.0 does)

Yes. It's time to put semver on the table. I did not notice that rtc authentication can bring in so much compatible issues.

To achieve that, we should maintain several long-term branches and cherry-pick compatible features/bug-fixes.

> furthermore you can add same feature (like handle an api endpoint) on all versions incrementing the “minor” number (without being crazy on specify which version works for which server).
>
> so your numbering scheme become .. , and using recent dependency tools like poetry (and probably also flit and setuptools), it will never suggest to upgrade 1.x to 2.x if this package is marked as “^1.0”.

That's right. Currently the most distinguished/incompatible change is #133. To get started, we can create 2 new branches (for release 1.x.x and 2.x.x) to separate that incompatible commit.

**Comment by gpongelli** [comment]
> > installing the package on project with poetry.
> 
> This sounds good good to me. Also I notice that `poetry` could bring us great benefit. Would you like to work on this?
> 
> > I mean something like
> > 1.0.0 for the actual 0.6.0
> > 2.0.0 for the actual 0.7.0
> > 3.0.0 for the actual 0.8.0
> > And so on
> > in this way, if I’m on 1.0.0, I know that 2.0.0 can generally break something (and effectively it does, 0.7.0 does not work for me but 0.6.0 does)
> 
> Yes. It's time to put semver on the table. I did not notice that rtc authentication can bring in so much compatible issues.
> 
> To achieve that, we should maintain several long-term branches and cherry-pick compatible features/bug-fixes.
> 
> > furthermore you can add same feature (like handle an api endpoint) on all versions incrementing the “minor” number (without being crazy on specify which version works for which server).
> > so your numbering scheme become .. , and using recent dependency tools like poetry (and probably also flit and setuptools), it will never suggest to upgrade 1.x to 2.x if this package is marked as “^1.0”.
> 
> That's right. Currently the most distinguished/incompatible change is #133. To get started, we can create 2 new branches (for release 1.x.x and 2.x.x) to separate that incompatible commit.

I can work adding poetry files on a new MR, I’ll link to this issue.

on the other way, to avoid managing multiple branches, it could be possible to do something like
1. Try access with most recent way (>=0.7.0)
2. If it raises exception, try previous way (0.6.0 way) saving somewhere which is the way that works

probably a better way to do this is to separate RTCClient in two different subclasses, making an object with one of them and if it fails, create the object with the other class.

What do you think ?

**Comment by dixudx** [comment]
> on the other way, to avoid managing multiple branches, it could be possible to do something like
>
>    Try access with most recent way (>=0.7.0)
>    If it raises exception, try previous way (0.6.0 way) saving somewhere which is the way that works
>
> probably a better way to do this is to separate RTCClient in two different subclasses, making an object with one of them and if it fails, create the object with the other class.

That's great. I'd love it. Maybe we only need to have a union combined auth function that converges two different auth methods.

**Comment by gpongelli** [comment]
> That's right. Currently the most distinguished/incompatible change is #133. To get started, we can create 2 new branches (for release 1.x.x and 2.x.x) to separate that incompatible commit.


About the [PR 133](https://github.com/dixudx/rtcclient/pull/133/files) , I've tested that the `auth` code does not interfere with login.
The point to focus on is the entire removed block of line 93-106 , just having that block back in my env from 0.8.2 tag does work (it's also strange that I need 0.6.0 version having jazz 7.0.2 but ok) .
Instead of having different branches or different client's subclasses (that could become a maintenance nightmare), a quick patch could be to wrap that part with a flag from the RTCClient init, like `ends_with_jazz`.

what do you think ?

**Comment by dixudx** [comment]
@gpongelli Now #184 could better handle the authentication incompatible issue. I think we can close this issue.
