### ISSUE TITLE
workitem: builtin attributes are obtained as link

### ISSUE THREAD

**Issue by gpongelli** [dixudx/rtcclient#177]
Hi, 
after the [previous issue](https://github.com/dixudx/rtcclient/issues/174), I finally get a workitem but, accessing its built-in attributes, I get links and not their real values.

code:
```python

    wk = myclient.getWorkitem(<work_item_id>)
    print(wk.comments)
    print(wk.description)
    print(wk.filedAgainst.values())
    print(wk.foundIn)
    print(wk.identifier)
    print(wk.plannedFor)
    print(wk.type)
    print(wk.state)
```

results:

- comment -> `{'@oslc_cm:collref': 'https://rationalcld.dl.net/ccm/oslc/workitems/<work_item_id>/rtc_cm:comments'}`
- description -> correct description in html text
- filedAgainst -> `{'@rdf:resource': 'https://rationalcld.dl.net/ccm/resource/itemOid/com.ibm.team.workitem.Category/<category_identifier>'}`
- foundIn -> `{'@rdf:resource': 'https://rationalcld.dl.net/ccm/resource/itemOid/com.ibm.team.workitem.Deliverable/<internal_identifier>'}`
- identifier -> correct number
- plannedFor -> `{'@rdf:resource': 'https://rationalcld.dl.net/ccm/oslc/iterations/<internal_identifier>'}`
- type -> `{'@rdf:resource': 'https://rationalcld.dl.net/ccm/oslc/types/<internal_identifier>/defect'}` < yes, I looked for a defect
- state -> `{'@rdf:resource': 'https://rationalcld.dl.net/ccm/oslc/workflows/<workflow_identifier>/states/com.ibm.team.workitem.defectWorkflow/com.ibm.team.workitem.defectWorkflow.state.s9'}` 

I've also tried the "values()", but I still get the link `dict_values(['https://rationalcld.dl.net/ccm/resource/itemOid/com.ibm.team.workitem.Category/<internal_identifier>'])`

Is there a way to get the "human readable" values instead of those links? 

Thanks,

Versions:
- rtcclient 0.6.0
- jazz server 7.0.2

**Comment by dixudx** [comment]
> it sounds a little strange that apackage that should convert xml to dictionary can led to this big difference. Any thoughts to change it ?

Quite a few people complain the incompatible change introduced from 0.13.0 in `xmltodict`. And no new versions are released to mitigate this issue. So currently we need to stick to `xmltodict<=0.12.0`.

In the `xmltodict` Github repo, we can find multiple issues are reported on version `0.13.0`.

> Any thoughts to change it ?

Well, we could. Any recommended libraries?

**Comment by gpongelli** [comment]
just pushed a fix https://github.com/dixudx/rtcclient/pull/178 that works with 0.13.0

**Comment by dixudx** [comment]
Close with PR #178
