### ISSUE TITLE
How can you add additional unsupported attributes beyond RTC Clients built-in attributes

### ISSUE THREAD

**Issue by scottlinuxden** [dixudx/rtcclient#189]
I have two fields I want to pull from RTC project that are not in RTC Client built-in attributes list.  Is there a method to add custom attributes or can you advise me on how to add them in the RTC client source?

**Comment by dixudx** [comment]
@scottlinuxden Please check whether [this doc](https://rtcclient.readthedocs.io/en/latest/quickstart.html#about-returned-properties) helps solve the problem.

Actually all the properties could be found from `field_alias`.

```
import pprint
# print the field alias
pprint.pprint(wk2.field_alias, width=1)
```

**Comment by scottlinuxden** [comment]
@dixudx I have looked at the field aliases and the two fields which are configured for each RTC work item is:

- Blocked
- Change Notes

Neither are listed and I imagine are specific to my company's RTC installation/configuration.  Can I just copy one of the methods in rtcclient and add the field name above to implement?  Seems like OLSC queries are being used.  The Blocked field is a checkbox on the RTC Work Item page and Change Notes is a text entry field.

**Comment by dixudx** [comment]
@scottlinuxden When you fetch a workitem, you can try to set param `skip_full_attributes=False` to see whether it works. 

```python
myclient.getWorkitem(workitem_id, skip_full_attributes=False)
```

Also, you could get the field link by accessing through field aliases. Let's see whether this works as well. With these field links, we could retrieve raw data and parse them to get what we want.

**Comment by scottlinuxden** [comment]
The fields are returned in getWorkItem which I could capture those for a single work item but change you suggest a way to get those assigned for getWorkItems since skip_full_attributes is not an argument to getWorkItems.  I could call getWorkItems and get all the work items and these call getWorkItem on each individual work item with skip_full_attributes=False but this would take a while to get hundreds of work items individually.

**Comment by scottlinuxden** [comment]
I was able to get the fields thru the returned_properties argument to getWorkItems.  I accessed the fields thru raw_data and used the properties rtc_cm:path to variable.  thanks for your help.

**Comment by scottlinuxden** [comment]
Resolved my issue
