### ISSUE TITLE
No Authentication Exception Raised and Client Session Expired

### ISSUE THREAD

**Issue by jianzj** [dixudx/rtcclient#70]
During my experiment, I just found one issue,
1) I found when I entered a wrong password, actually it does not raise an Authentication failed exception , but a TypeError, maybe this should be changed.

2) Another is about if could add a new feature to decide is a client session is available or not, or reload this client session when it is unavailable.

**Comment by dixudx** [comment]
@jianzj I've already fix the session expiration. Will take further steps to test this patchset.

You can also test this patchset against your Jazz/RTC environment if you would like. I really appreciate that.

Thanks for your efforts.

**Comment by dixudx** [comment]
* close this issue with above fixing commits;
* implemented new feature on client session expiration;

**Comment by rajueekgp** [comment]
@dixudx while running runSavedQueryByUrl, I am getting the below response in error log

with response: b'<?xml version="1.0" encoding="UTF-8"?><oslc_cm:error xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/">\n<oslc_cm:status>500</oslc_cm:status>\n<oslc_cm:message>Query _Vfx3sLcFEequ0Y6VfgebEw expired.</oslc_cm:message>\n</oslc_cm:error>


it seems like the query token has been expired. Can you please give resolution to it

**Comment by dixudx** [comment]
@rajueekgp The token is usually generated and maintained on the server side. You can try to regenerate one through web UI.

Or you can just use [original query items](https://rtcclient.readthedocs.io/en/latest/quickstart.html#query-workitems) instead of this expired token.
