### ISSUE TITLE
Please add support to fetch Changes in a ChangeSet

### ISSUE THREAD

**Issue by sglebs** [dixudx/rtcclient#72]
First of all, thanks for the library!

I need to traverse the changes in a ChangeSet, much like http://stackoverflow.com/questions/24628644/how-to-get-changesetall-files-changes-from-iworkitem-item-by-program

I presume that, just like the getChangeSets in WorkItem, I need to add a getChanges method in class ChangeSet ? I presume the class Changes also needs to be created?

Thanks!

**Comment by dixudx** [comment]
Thanks for using this library.

I did intend to implement such method (getting a list of file names that the changeset contains) when writing this library. But I did not find a good scenario for using this method, which seemed to be useless. Thanks for pushing me forward.

Now I wanna know you want just the filenames or the actual files.

I really appreciate that you would join me together to implement this small method.

**Comment by sglebs** [comment]
I want to run metrics BEFORE and AFTER on files that were touched, and feed that into a metrics panel of ours (mobile app). This way we can see, for example, if McCabe went up and by how much in the files that were touched.

So, my actual need is to go from the work item to the changeset, and for each change in the changesets  get the files and get a reference to the "just-before" and "just-after"states/versions of the files and check those 2 versions out, into 2 separate root folders, BEFORE and AFTER. After I have the full set of files that were touched/changed stored in these 2 local folders, I will run my other script which compares the metrics: https://github.com/sglebs/udbcmp

Makes sense? Thanks!

**Comment by dixudx** [comment]
Sounds like `git diff` and `patch`, right ?

**Comment by sglebs** [comment]
Yeah, something like that. Before, After, delta-metrics on them.

**Comment by dixudx** [comment]
Hi @sglebs ,

Please checkout the newest code (`git checkout -b development https://github.com/dixudx/rtcclient`) to your site-packages (or a folder your Python can find).

Below is a sample code. You can have a try.

```python
from rtcclient import RTCClient
from rtcclient.utils import setup_basic_logging


if __name__ == "__main__":
    setup_basic_logging()
    url = "https://xx.xx.xx:9443/jazz"
    username = "you@youremail.com"
    password = "CHANGEME"
    rtcc = RTCClient(url, username, password,
                     ends_with_jazz=True)

    wk = rtcc.getWorkitem(144810)

    changesets = wk.getChangeSets()
    changes = changesets[0].getChanges()
    change = changes[0]
    change.fetchBeforeStateFile("/Users/stephen/test_before")
    change.fetchAfterStateFile("/Users/stephen/test_after")

```

**Comment by sglebs** [comment]
Thanks, I will give it a try. I changed my requirements.txt like so:
```
#rtcclient==0.5.0
git+git://github.com/dixudx/rtcclient.git@development
```
but I am getting an error:

```
(env) sglebs:rtcdelta mqm$ pip install -r requirements.txt 
Collecting git+git://github.com/dixudx/rtcclient.git@development (from -r requirements.txt (line 3))
  Cloning git://github.com/dixudx/rtcclient.git (to development) to /var/folders/ts/c1cr6kcd4yb6s7tj6bjt_nyr0000gp/T/pip-amx2ussj-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/ts/c1cr6kcd4yb6s7tj6bjt_nyr0000gp/T/pip-amx2ussj-build/setup.py", line 21, in <module>
        pbr=True)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 626, in easy_install
        not self.always_copy, self.local_index
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/setuptools/package_index.py", line 601, in fetch_distribution
        return dist.clone(location=self.download(dist.location, tmpdir))
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/setuptools/package_index.py", line 517, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/setuptools/package_index.py", line 758, in _download_url
        return self._attempt_download(url, filename)
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/setuptools/package_index.py", line 764, in _attempt_download
        headers = self._download_to(url, filename)
      File "/Users/mqm/git/rtcdelta/env/lib/python3.5/site-packages/setuptools/package_index.py", line 680, in _download_to
        block = fp.read(bs)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 433, in read
        n = self.readinto(b)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 473, in readinto
        n = self.fp.readinto(b)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 924, in recv_into
        return self.read(nbytes, buffer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 786, in read
        return self._sslobj.read(len, buffer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 570, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/ts/c1cr6kcd4yb6s7tj6bjt_nyr0000gp/T/pip-amx2ussj-build/
(env)sglebs:rtcdelta mqm$ 
```
I am trying to get it fixed first.

**Comment by dixudx** [comment]
This seems to be the installation error that not relates to rtcclient.

That usually happens because of weak internet connection i.e; loss of internet connection during installation redo the command and it should work fine.

**Comment by dixudx** [comment]
Also you may consider change the default pypi index sever

**Comment by sglebs** [comment]
It was a network maintenance problem. It was fixed and the code worked, take a look: https://github.com/sglebs/rtcdelta/blob/master/rtcdelta.py

Thanks!

I see one potential source of problems. In java I could have 2 files:

1.  com/foo/Pixel.java
2.  com/bar/Pixel.java

If both files are touched (in the changes), when I get them via your fetchBeforeStateFile API I need the namespace to be preserved or they will override each other. So, my question: is there a notion of full relative path for a file in the changeset? If so, perhaps I could have a keyword parameter to fetchBeforeStateFile where I say if I want to preserve the full relative name/nesting relative to the root? Or maybe be the other way aroud - preserve by default and only flatten if I request it (flatten=True).

Makes sense?

**Comment by dixudx** [comment]
You mean the put these two new created files into a single changeset. And there will be 2 changes in this  changeset. From the changes, you can check out these two files to the specified file folders.

Now the question you met was that you cannot get the relative file path, only the checkout file names.

Actually I've met such a problem when implementing this feature. But still trying to figure it out.

**Comment by sglebs** [comment]
Yes, I mean one single changes having 2 files changed, where these files have different fully qqualified names (full paths) but same simple names. Example: com/foo/Pixel.java and com/bar/Pixel.java . The fully qualified names are different but the simple names are the same (Pixel.java).

In languages like Delphi/Pascal, it won't be the namespace but the original directory subtree. Example: src/core/Foo.pas . There could be another file src/utils/Foo.pas. If I change both in the same changes, the simple names will be Foo.pas.

This is why I think the simplest solution is to use the original files's path relative to the pro root dir and honor/preserve that in your new API. If people pass flatten=True than you do it the way you are already doing (ignore the relative path). But I think you should preserve the relative path when fetching.

The question is: can it be done? Do you have this info available? (relative path)

**Comment by dixudx** [comment]
I don't know. Still searching methods and apis that can help implementing this problem. 

If you find a good solution, you can submit the codes here by submitting a PR.

Thanks for your efforts.

**Comment by dixudx** [comment]
@sglebs I tried several ways to get the full/relative file path, but no results.

![image](https://cloud.githubusercontent.com/assets/5449021/13976643/c131dc92-f0fc-11e5-91ec-32980c496327.png)

From the above webpage, only filenames are given/displayed. And I use Firebug and find nothing useful for this problem.

Currently we have to stop here until we can find other ways to solve this.

**Comment by sglebs** [comment]
Is it possible to go from the change to the file entity itself and then ask the file object itself for its relative path?

**Comment by dixudx** [comment]
Didn't find a way to get there. I've already tried before.
