### ISSUE TITLE
Unable to create work item due to posting to wrong url

### ISSUE THREAD

**Issue by leejian0612** [dixudx/rtcclient#73]
seems the slash before "/oslc/contexts" should be ignored.
https://github.com/dixudx/rtcclient/blame/542feccec23ff7afeb24406ec6e56dc82792f025/rtcclient/client.py#L1049

**Comment by dixudx** [comment]
@leejian0612 You're right. Thanks for pointing this out. Already fix it.

**Comment by wang850228803** [comment]
This fix is still not merged to the code. Is the code still in maintenance?

**Comment by dixudx** [comment]
@wang850228803 Will merge into master branch later and release to `0.6.0`. [Visit milestone 0.6.0](https://github.com/dixudx/rtcclient/milestone/6) for more information. 

Currently you can patch this fix by checking out `development` branch.

Thanks for using this library. Sorry for the inconvenience.

**Comment by dixudx** [comment]
@wang850228803 Already released `0.6.0`. You can install directly by `pip install -U rtcclient`
