### ISSUE TITLE
Check condition for missing params seems wrong

### ISSUE THREAD

**Issue by leejian0612** [dixudx/rtcclient#74]
when missing_attributes is "[]", the check condition will return true, and will output 

> rtcclient.exception.EmptyAttrib: Missing Parameters: []

so seems we need to change it to 

```python
missing_attributes = parameters.difference(input_attributes)
if missing_attributes:
    error_msg = "Missing Parameters: %s" % list(missing_attributes)
    self.log.error(error_msg)
    raise exception.EmptyAttrib(error_msg)
else:
    self.log.debug("No missing parameters")
```
https://github.com/dixudx/rtcclient/blob/master/rtcclient/client.py#L1154

**Comment by dixudx** [comment]
How come `missing_attributes` is `[]`? Can you elaborate it with some real data (remove the confidential parts)?

**Comment by leejian0612** [comment]
This is the template,  I used to create item,
<oslc_cm:ChangeRequest xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/" xmlns:calm="http://jazz.net/xmlns/prod/jazz/calm/1.0/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/terms/" xmlns:oslc_pl="http://open-services.net/ns/pl#" xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
        <rtc_cm:filedAgainst rdf:resource="_OZKIMPcQEeW6Du_oKvKbfw"></rtc_cm:filedAgainst>
        <oslc_cm:priority rdf:resource="{{ priority }}"></oslc_cm:priority>
        <dc:description>{{ description }}</dc:description>
        <dc:title>{{ title }}</dc:title>
        <oslc_cm:severity rdf:resource="{{ severity }}"></oslc_cm:severity>
</oslc_cm:ChangeRequest>

This is the fields should be provided from the client:
>>> myclient.listFields('template')
set(['priority', 'title', 'severity', 'description'])

last  is the commend used to create rtc item,
myclient.createWorkitem('Defect', description="just a test for using python rtcclient", title="ljianbj_test_rtcclient", projectarea_name='Bluemix Landing CDL Test', priority="Unassigned", severity="Critical" ,template='template')

I provided the needed fields for 'template', including title, description, priority, and severity,  so when run to code 1154, the "not missing_attributes" will return true, but  we do not missing any params here.
(Pdb) p input_attributes
set(['priority', 'severity'])
(Pdb) p parameters
set(['priority', 'severity'])
(Pdb) p missing_attributes
set([])
(Pdb) print not missing_attributes
True

**Comment by dixudx** [comment]
Gotcha.

```python
missing_attributes = parameters.difference(input_attributes)
```

when `input_attributes` gets all the needed attributes that defined in `parameters`, `missing_attributes` will be `set([])`. Under this circumstance, `not missing_attributes` is `True` instead of `False`.

**Comment by dixudx** [comment]
@leejian0612 check out the development branch and have another try. Sorry for this bug.

**Comment by leejian0612** [comment]
@dixudx thanks for your quick update, and the fix works for me now!
