### ISSUE TITLE
Does it support RTC 6.0+?

### ISSUE THREAD

**Issue by lioramilbaum** [dixudx/rtcclient#75]

**Comment by dixudx** [comment]
Actually I have not run fully tests. But I have tested that most of the methods work quite well on RTC 6.0+.

You can have another try.

**Comment by dixudx** [comment]
@lioramilbaum any issues encountered ?

**Comment by lioramilbaum** [comment]
Didn't try it yet.

**Comment by dixudx** [comment]
@lioramilbaum Feel free to reopen it. Thanks.
