### ISSUE TITLE
It's better to add http-proxy feature

### ISSUE THREAD

**Issue by edeuser** [dixudx/rtcclient#78]
Hi, 
Is that possible to add http-proxy feature ? Since in some senario this is really necessary.

Thank you.

**Comment by dixudx** [comment]
@edeuser I've already enabled proxy feature, supporting both http/https and socks based proxy.

Would you please run another tests against this new feature ? I want to make sure that all works well on your environment.

**Comment by dixudx** [comment]
@edeuser Any good news?
