### ISSUE TITLE
How do I determine the string to use in a search by state?

### ISSUE THREAD

**Issue by durera** [dixudx/rtcclient#80]
If I look at the resource definition of one of the workitem I can want to find in a search by state I can see the state is:

`<rtc_cm:state rdf:resource="https://HOST:PORT/ccm/oslc/workflows/_QkWKkBrqEeOPqO0PvYSycg/states/com.ibm.team.workitem.defectWorkflow/3"/>`

In the documentation it states that to search by state you should do something like:

`query_str = ('dc:type="defect" and ''rtc_cm:state!="default_workflow.state.s1" and ''dc:subject="bvt"')`

How do I convert from what I see in the resource I am trying to find into what I should be entering in my query?  I have tried all kinds of variants of something.state.somethingElse that I can think of based on the rdf value, none of which return any result.

Is there a way I can get the state object of something I retrieve using this client library and call getStringId() or somesuch to work backwards from having the state object to getting the string ID I need to use in a query perhaps?

**Comment by dixudx** [comment]
@durera 

You can try to follow below script.

```
>>> # init your rtc client first
>>> mywk_id = 123456
>>> myworkitem = myclient.getWorkitem(mywk_id)
>>> wk_all_states = myworkitem.getStates()
```

Now you've got all the available states of this workitem. And then try to filter/loop over the list `wk_all_states` and find the state whose url (`wk_state.url`) is `https://HOST:PORT/ccm/oslc/workflows/_QkWKkBrqEeOPqO0PvYSycg/states/com.ibm.team.workitem.defectWorkflow/3`

```
>>> target_state = [wk_state for wk_state in wk_all_states if wk_state.url == "https://HOST:PORT/ccm/oslc/workflows/_QkWKkBrqEeOPqO0PvYSycg/states/com.ibm.team.workitem.defectWorkflow/3"]
>>> print(target_state.identifier)
```

`target_state.identifier` is what you want.

**Comment by durera** [comment]
Excellent, that did the trick ... it was painfully simple in the end .. the value i needed was simply `rtc_cm:state="3"`, I was tripping myself up trying to form something in the form "x.state.y" based on the example and never even tried the blindingly obvious option here :)

**Comment by dixudx** [comment]
@durera So glad that the problem is solved.

Closed.
