### ISSUE TITLE
Please add provision to get root categories from a project area

### ISSUE THREAD

**Issue by Karthik9479** [dixudx/rtcclient#83]
Hi,

The method `RTCClient.getFiledAgainsts()` provides a list of class which supports only `title`.

It would be useful to get only the root categories (depth=0) from a project area. 

Thank you,

**Comment by dixudx** [comment]
Thanks for using this library.

1. The method `getFiledAgainsts()` will return a list of `rtcclient.models.FiledAgainst` objects, where you can aceess `someFiledAgainst.title`, `someFiledAgainst.hierarchicalName`, `someFiledAgainst.depth` and etc. Such alias can be retrieved by accessing `someFiledAgainst.field_alias`

2. For `FiledAgainst` with `depth=0`, you can just run
   ```python
   # init yourRTCClient first
   filedAgainsts = yourRTCClient.getFiledAgainsts(archived=False)
   rootFiledAgainsts = list()
   for fa in filedAgainsts:
       if fa.depth == '0':
              rootFiledAgainsts.append(fa)
   ```

**Comment by Karthik9479** [comment]
Thanks @dixudx for this, Works fine as requested.

I was looking at the code and the getFiledAgainsts() was returning list of type rtcclient.models.FiledAgainst.

In the models.py, it was returning the `self.title` and wasn't sure what other properties were returned. I will dig into the code more or try printing it out.


Thanks again for this great framework.
