### ISSUE TITLE
'RTCClient' object has no attribute 'getFiledagainst'

### ISSUE THREAD

**Issue by wang850228803** [dixudx/rtcclient#86]
When the keyword is 'filedAgainst', 'keyword_cls' value will be 'self.getFiled**a**gainst'. But 'self.getFiled**A**gainst' is expected.
[https://github.com/dixudx/rtcclient/blame/master/rtcclient/client.py#L1157](url)

**Comment by dixudx** [comment]
@wang850228803 Yes, you're right. `keyword.capitalize()` did not behave as what I expected. Will fix it later.

**Comment by dixudx** [comment]
@wang850228803 Please try this patchset on your environment.
