### ISSUE TITLE
Workitem creation

### ISSUE THREAD

**Issue by Feva** [dixudx/rtcclient#87]
I have tried many ways but have not found how to create a workitem.
I have used a template, copy from inside the createWorkitem and copyWorkitem.
All appear to generate an error.
I either get a 500 error or 404 (stating it cannot find the work item type I am trying to create)

Doe this work? 
Could you please provide and example which I can work from?

**Comment by dixudx** [comment]
@Feva Of course, it works. We've already tested against many times. For detailed api doc, please refer to [client doc](http://rtcclient.readthedocs.io/en/latest/client.html).

```python
>>> from rtcclient.utils import setup_basic_logging
>>> from rtcclient import RTCClient
# you can remove this if you don't need logging
# default debug logging for console output
>>> setup_basic_logging()
# url ends with jazz
>>> url = "https://your_domain:9443/jazz"
>>> username = "your_username"
>>> password = "your_password"
# if your rtc server is behind a proxy, remember to set "proxies"
# explicitly. detailed can be found in quick start of the doc
# if your url ends with ccm, set ends_with_jazz to False
# refer to issue #68 for detailed explanation
>>> myclient = RTCClient(url, username, password, ends_with_jazz=True)
>>> new_workitem = myclient. createWorkitem("your_item_type", "your_title", **kwargs)
```

The method `createWorkitem` supports many parameters, you can visit the doc for detailed explanations.

In order to quickly identify the root cause, please enable logging by using `setup_basic_logging()`. You can modify the log level as well. We could find more from the log information.

**Comment by Feva** [comment]
@dixudx I'll try and supply a generic example if my problem. I just can't get it to work.

**Comment by dixudx** [comment]
@Feva Also you may need to identify the right item type in your rtc env, which may have already been modified to other values.

**Comment by Feva** [comment]
@dixudx Code is as follows:

from rtcclient.utils import setup_basic_logging
from rtcclient.client import RTCClient

setup_basic_logging()
url = "http://exelrtc6dev/ccm"
username = "###"
password = "###"
myclient = RTCClient(url, username, password, ends_with_jazz=False, searchpath='templates')

# Created a simple 'Task' manually via web view.
# Set the summary and description.
# Left all other fields as default. Most are flagged as 'Unassigned'
# Tried to copy the item.
wi = myclient.copyWorkitem(65868, title="Task summary copy 1", description = "Task description copy 1")

print wi


The error at the end of the output is:

2017-05-26 09:37:17,256 DEBUG client.RTCClient: Post a request to http://exelrtc6dev/ccm/oslc/contexts/_p017cM-1EeO2IM9bCWjODg/workitems/Task with data: <?xml version="1.0" encoding="UTF-8"?>
<oslc_cm:ChangeRequest xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/" xmlns:calm="http://jazz.net/xmlns/prod/jazz/calm/1.0/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/terms/" xmlns:oslc_pl="http://open-services.net/ns/pl#" xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
        <rtc_cm:requiresuserguidechange>false</rtc_cm:requiresuserguidechange>
        <rtc_cm:userguidecontentupdated>false</rtc_cm:userguidecontentupdated>
        <rtc_cm:researchanddevelopment>false</rtc_cm:researchanddevelopment>
        <dc:subject></dc:subject>
        <rtc_cm:filedAgainst rdf:resource="http://exelrtc6dev/ccm/resource/itemOid/com.ibm.team.workitem.Category/_qix_gM-1EeOJl_ontXo1cA"></rtc_cm:filedAgainst>
        <oslc_cm:priority rdf:resource="http://exelrtc6dev/ccm/oslc/enumerations/_p017cM-1EeO2IM9bCWjODg/priority/priority.literal.l07"></oslc_cm:priority>
        <rtc_cm:estimate></rtc_cm:estimate>
        <rtc_cm:due></rtc_cm:due>
        <rtc_cm:correctedEstimate></rtc_cm:correctedEstimate>
        <dc:description>Task description copy 1</dc:description>
        <rtc_cm:plannedFor></rtc_cm:plannedFor>
        <rtc_cm:ownedBy rdf:resource="http://exelrtc6dev/jts/users/unassigned"></rtc_cm:ownedBy>
        <oslc_cm:severity rdf:resource="http://exelrtc6dev/ccm/oslc/enumerations/_p017cM-1EeO2IM9bCWjODg/severity/severity.literal.l3"></oslc_cm:severity>
        <dc:title>Task summary copy 1</dc:title>
        <rtc_cm:foundIn></rtc_cm:foundIn>
        <rtc_cm:approvals></rtc_cm:approvals>
        <rtc_cm:approvalTasks></rtc_cm:approvalTasks>
        <rtc_cm:archived>false</rtc_cm:archived>
        <rtc_cm:releasenoteheader></rtc_cm:releasenoteheader>
        <rtc_cm:releasenotedetail></rtc_cm:releasenotedetail>
        <rtc_cm:databasechangepending>false</rtc_cm:databasechangepending>
        <rtc_cm:releasenotesrequired>false</rtc_cm:releasenotesrequired>
        <rtc_cm:module></rtc_cm:module>
        <rtc_cm:teamArea rdf:resource="http://exelrtc6dev/ccm/oslc/teamareas/_0jaooNBSEeOoh5464SCfyw"></rtc_cm:teamArea>
</oslc_cm:ChangeRequest> and json: None
2017-05-26 09:37:17,259 DEBUG requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): exelrtc6dev
2017-05-26 09:37:17,267 DEBUG requests.packages.urllib3.connectionpool: http://exelrtc6dev:80 "POST /ccm/oslc/contexts/_p017cM-1EeO2IM9bCWjODg/workitems/Task HTTP/1.1" 404 216
2017-05-26 09:37:17,269 ERROR client.RTCClient: Failed POST request at <http://exelrtc6dev/ccm/oslc/contexts/_p017cM-1EeO2IM9bCWjODg/workitems/Task> with response: <?xml version="1.0" encoding="UTF-8"?><oslc_cm:error xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/">
<oslc_cm:status>404</oslc_cm:status>
<oslc_cm:message>Not found: Task</oslc_cm:message>
</oslc_cm:error>
2017-05-26 09:37:17,269 INFO client.RTCClient: 404
Traceback (most recent call last):
  File "copyWIsimple.py", line 14, in <module>
    wi = myclient.copyWorkitem(65868, title="Task summary copy 1", description = "Task description copy 1")
  File "C:\Python27\lib\site-packages\rtcclient\client.py", line 1113, in copyWorkitem
    return self._createWorkitem(wi_url_post, wi_raw)
  File "C:\Python27\lib\site-packages\rtcclient\client.py", line 1121, in _createWorkitem
    data=workitem_raw)
  File "C:\Python27\lib\site-packages\rtcclient\utils.py", line 26, in wrapper
    resp = func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\rtcclient\base.py", line 123, in post
    response.raise_for_status()
  File "C:\Python27\lib\site-packages\requests\models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://exelrtc6dev/ccm/oslc/contexts/_p017cM-1EeO2IM9bCWjODg/workitems/Task

**Comment by Feva** [comment]
@dixudx Sorry, my comments have come out large in the above!

**Comment by Feva** [comment]
@dixudx If I try and do a createWorkitem with the same details and 'Keep=True' passed I get a different error:

2017-05-26 09:47:44,114 INFO client.RTCClient: Start to create a new <Task> with raw data: <?xml version="1.0" encoding="UTF-8"?>
<oslc_cm:ChangeRequest xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/" xmlns:calm="http://jazz.net/xmlns/prod/jazz/calm/1.0/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/terms/" xmlns:oslc_pl="http://open-services.net/ns/pl#" xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
        <rtc_cm:requiresuserguidechange>false</rtc_cm:requiresuserguidechange>
        <rtc_cm:userguidecontentupdated>false</rtc_cm:userguidecontentupdated>
        <rtc_cm:researchanddevelopment>false</rtc_cm:researchanddevelopment>
        <dc:subject></dc:subject>
        <rtc_cm:filedAgainst rdf:resource="http://exelrtc6dev/ccm/resource/itemOid/com.ibm.team.workitem.Category/_qix_gM-1EeOJl_ontXo1cA"></rtc_cm:filedAgainst>
        <oslc_cm:priority rdf:resource="http://exelrtc6dev/ccm/oslc/enumerations/_p017cM-1EeO2IM9bCWjODg/priority/priority.literal.l07"></oslc_cm:priority>
        <rtc_cm:estimate></rtc_cm:estimate>
        <rtc_cm:due></rtc_cm:due>
        <rtc_cm:correctedEstimate></rtc_cm:correctedEstimate>
        <dc:description>Test description create 1</dc:description>
        <rtc_cm:plannedFor></rtc_cm:plannedFor>
        <rtc_cm:ownedBy rdf:resource="http://exelrtc6dev/jts/users/unassigned"></rtc_cm:ownedBy>
        <oslc_cm:severity rdf:resource="http://exelrtc6dev/ccm/oslc/enumerations/_p017cM-1EeO2IM9bCWjODg/severity/severity.literal.l3"></oslc_cm:severity>
        <dc:title>Test summary create 1</dc:title>
        <rtc_cm:foundIn></rtc_cm:foundIn>
        <rtc_cm:approvals></rtc_cm:approvals>
        <rtc_cm:approvalTasks></rtc_cm:approvalTasks>
        <rtc_cm:archived>false</rtc_cm:archived>
        <rtc_cm:releasenoteheader></rtc_cm:releasenoteheader>
        <rtc_cm:releasenotedetail></rtc_cm:releasenotedetail>
        <rtc_cm:databasechangepending>false</rtc_cm:databasechangepending>
        <rtc_cm:releasenotesrequired>false</rtc_cm:releasenotesrequired>
        <rtc_cm:module></rtc_cm:module>
        <rtc_cm:teamArea rdf:resource="http://exelrtc6dev/ccm/oslc/teamareas/_0jaooNBSEeOoh5464SCfyw"></rtc_cm:teamArea>
</oslc_cm:ChangeRequest>
2017-05-26 09:47:44,115 DEBUG client.RTCClient: Post a request to http://exelrtc6dev/ccm/oslc/contexts/_p017cM-1EeO2IM9bCWjODg/workitems/task with data: <?xml version="1.0" encoding="UTF-8"?>
<oslc_cm:ChangeRequest xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/" xmlns:calm="http://jazz.net/xmlns/prod/jazz/calm/1.0/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/terms/" xmlns:oslc_pl="http://open-services.net/ns/pl#" xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
        <rtc_cm:requiresuserguidechange>false</rtc_cm:requiresuserguidechange>
        <rtc_cm:userguidecontentupdated>false</rtc_cm:userguidecontentupdated>
        <rtc_cm:researchanddevelopment>false</rtc_cm:researchanddevelopment>
        <dc:subject></dc:subject>
        <rtc_cm:filedAgainst rdf:resource="http://exelrtc6dev/ccm/resource/itemOid/com.ibm.team.workitem.Category/_qix_gM-1EeOJl_ontXo1cA"></rtc_cm:filedAgainst>
        <oslc_cm:priority rdf:resource="http://exelrtc6dev/ccm/oslc/enumerations/_p017cM-1EeO2IM9bCWjODg/priority/priority.literal.l07"></oslc_cm:priority>
        <rtc_cm:estimate></rtc_cm:estimate>
        <rtc_cm:due></rtc_cm:due>
        <rtc_cm:correctedEstimate></rtc_cm:correctedEstimate>
        <dc:description>Test description create 1</dc:description>
        <rtc_cm:plannedFor></rtc_cm:plannedFor>
        <rtc_cm:ownedBy rdf:resource="http://exelrtc6dev/jts/users/unassigned"></rtc_cm:ownedBy>
        <oslc_cm:severity rdf:resource="http://exelrtc6dev/ccm/oslc/enumerations/_p017cM-1EeO2IM9bCWjODg/severity/severity.literal.l3"></oslc_cm:severity>
        <dc:title>Test summary create 1</dc:title>
        <rtc_cm:foundIn></rtc_cm:foundIn>
        <rtc_cm:approvals></rtc_cm:approvals>
        <rtc_cm:approvalTasks></rtc_cm:approvalTasks>
        <rtc_cm:archived>false</rtc_cm:archived>
        <rtc_cm:releasenoteheader></rtc_cm:releasenoteheader>
        <rtc_cm:releasenotedetail></rtc_cm:releasenotedetail>
        <rtc_cm:databasechangepending>false</rtc_cm:databasechangepending>
        <rtc_cm:releasenotesrequired>false</rtc_cm:releasenotesrequired>
        <rtc_cm:module></rtc_cm:module>
        <rtc_cm:teamArea rdf:resource="http://exelrtc6dev/ccm/oslc/teamareas/_0jaooNBSEeOoh5464SCfyw"></rtc_cm:teamArea>
</oslc_cm:ChangeRequest> and json: None
2017-05-26 09:47:44,115 DEBUG requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): exelrtc6dev
2017-05-26 09:47:44,184 DEBUG requests.packages.urllib3.connectionpool: http://exelrtc6dev:80 "POST /ccm/oslc/contexts/_p017cM-1EeO2IM9bCWjODg/workitems/task HTTP/1.1" 500 184
2017-05-26 09:47:44,184 ERROR client.RTCClient: Failed POST request at <http://exelrtc6dev/ccm/oslc/contexts/_p017cM-1EeO2IM9bCWjODg/workitems/task> with response: <?xml version="1.0" encoding="UTF-8"?><oslc_cm:error xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/">
<oslc_cm:status>500</oslc_cm:status>
<oslc_cm:message/>
</oslc_cm:error>
2017-05-26 09:47:44,186 INFO client.RTCClient: 500
Traceback (most recent call last):
  File "createWI.py", line 27, in <module>
    keep=True,
  File "C:\Python27\lib\site-packages\rtcclient\client.py", line 1073, in createWorkitem
    return self._createWorkitem(wi_url_post, wi_raw)
  File "C:\Python27\lib\site-packages\rtcclient\client.py", line 1121, in _createWorkitem
    data=workitem_raw)
  File "C:\Python27\lib\site-packages\rtcclient\utils.py", line 26, in wrapper
    resp = func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\rtcclient\base.py", line 123, in post
    response.raise_for_status()
  File "C:\Python27\lib\site-packages\requests\models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://exelrtc6dev/ccm/oslc/contexts/_p017cM-1EeO2IM9bCWjODg/workitems/task

**Comment by dixudx** [comment]
@Feva Would you please paste your log in [github gist](https://gist.github.com/) where we can easily track that.

**Comment by Feva** [comment]
@dixudx Never used that. Is the below correct?

https://gist.github.com/Feva/9676234a7027dd490da830a273844f8f

**Comment by dixudx** [comment]
@Feva Have you tried the method I pasted in [your gist](https://gist.github.com/Feva/9676234a7027dd490da830a273844f8f).

**Comment by Feva** [comment]
@dixudx I have updated it and tried it but still get a similar error message.

**Comment by Mershl** [comment]
@Feva do you get a 404 or 500 HTTP error?

**Comment by dixudx** [comment]
The error message for code 500 was quite short. Cannot find any more useful information. It is weird.

**Comment by Feva** [comment]
@dixudx For the create one it was a 404 error:

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://exelrtc6dev/ccm/oslc/types/_p017cM-1EeO2IM9bCWjODg/workitems/task

**Comment by dixudx** [comment]
Closed. Duplicate to issue #88
