### ISSUE TITLE
Create workitem of type 'Epic' - HTTP 404

### ISSUE THREAD

**Issue by Mershl** [dixudx/rtcclient#90]
Hi @dixudx 

When trying to create a workitem with a task_type of 'Epic' the task_type will be found by `projectarea.getItemType(item_type)` but on creation it will report:
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://<jazzhost>/ccm/oslc/contexts/_qi848CJaEeSy9NmiE0zU4Q/workitems/com.ibm.team.apt.workitemtype.epic
```
In the log it's visible as:
```
<oslc_cm:status>404</oslc_cm:status>
<oslc_cm:message>Not found: com.ibm.team.apt.workitemtype.epic</oslc_cm:message>
</oslc_cm:error>
```

**Comment by dixudx** [comment]
@Mershl Can you successfully create an Epic from the web UI ?

**Comment by Mershl** [comment]
@dixudx Yes, just tested. Is the service url provided by the service catalog possibly wrong?

**Comment by dixudx** [comment]
@Mershl Sorry, it's my mistake. This bug was involved by issue #88. Already fix that. Please have another try.

**Comment by Mershl** [comment]
@dixudx Thanks for the update. I've cut down my implementation to a minimum working example (basically just calling createWorkitem with a type, title, description, PA and a copied_from task).
For type 'Task' and 'Epic' _createWorkitem raises Client Error 409:
```
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://<jazzhost>/ccm/oslc/contexts/_2oS9cE8nEeaEVMF1sYTWPA/workitems/task

```

**Comment by dixudx** [comment]
@Mershl I retested the latest code of branch `development`. It works well on **Task** and **Epic**.

```python
my_rtc = RTCClient(.....)
new_workitem = my_rtc.createWorkitem("Epic", "client test", "test desc", "_73iaQFM1EeeSvaa7xqfEqw", copied_from=9, keep=True)
```

Please pull the latest code and retry.

If still the same error, please paste your sample workitem (already created successfully) xml here. We may need to compare the item type.

**Comment by Mershl** [comment]
Hi @dixudx, I found the culprit. I get a 
```
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://<jazzhost>/ccm/oslc/contexts/_2oS9cE8nEeaEVMF1sYTWPA/workitems/task
```
if I set `keep=False` when creating an Epic. Leaving it at `True` will create the Epic as intended.

**Comment by dixudx** [comment]
@Mershl Glad to see it works on your environment. Good job.

Actually you should **copy from a workitem with same type**. Because different workitems tend to have different attributes, which may result in such occurrences.

**Comment by Mershl** [comment]
@dixudx How long does it usually take for you to create an Epic/Task? Creating an Epic takes about 43 seconds and a Task averages at 40 seconds per creation on my two tested RTC installations.

**Comment by dixudx** [comment]
@Mershl Just a few seconds. Before posting request to create new workitem, the client will try to fetch some metadata to copy into the post body, which will take several seconds.

In general, it takes about 5-6 seconds.

**Comment by Mershl** [comment]
The problem is solved. Just one last question @dixudx. Have you ever tried calling Create in a thread pool. I have additional parameters that lead to a creation of ~40s. Using multithreads it should be possible to mititgate this time for 10 WorkItem creations.

**Comment by dixudx** [comment]
@Mershl Good question.

Actually using multithread will bring some benefits, mainly saving time. But RTC is mainly for project managements. Time efficiency is not that significant. Also the code structure, asynchronous callings and etc will make the library complicated and error-prone.

If we want to create tens of workitems simultaneously, we can just call `createWorkitem` in `threading.Thread` instead of creating one by one.

**Comment by Mershl** [comment]
Thanks @dixudx. Using threads it's possible to create 10 (and possibily more) Workitems at a time.
```
Creating 10 tasks sequentially: 430 seconds
Creating 10 tasks in parallel: 62 seconds
(Tasks include many custom attributes)
```
