### ISSUE TITLE
Authentication not working for bad login in 6.0.3

### ISSUE THREAD

**Issue by Feva** [dixudx/rtcclient#92]
We are running RTC 6.0.3

If I create an RTCClient object with a bad login I do not get an exception.

In client.py inside _get_headers there is a check for authfailed. This returns None for a good or bad login and not the text tested for.

For a bad login the headers returned are:

{'Transfer-Encoding': 'chunked', 'Date': 'Wed, 07 Jun 2017 15:12:30 GMT', 'Location': 'http://rtc/ccm/auth/authfailed', 'Content-Language': 'en-GB', 'X-Powered-By': 'Servlet/3.0'}

For a good login you get:

{'Content-Language': 'en-GB', 'X-Powered-By': 'Servlet/3.0', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'LtpaToken2=YjuJyUMB45rO29l9o2USsHEpz+Culer2BO9H0WLRRIKeBCBz3oDytevUzg68tl2MwxxLM6hrv8YyX/jxSMXFuYgrmHMR+7hiUkfZGM8zlTF+2aZATavcVGwXSpGx5h+hi3n9pysPUXfmBFALVgf6eO0s6quLqCaCXyIlPYkTyfpcTTl7ncAdo0TvncHSytESXNh0lM19R+OP+KPXBXoZfZWZi8jWXJk+ErHZyjzWcJ2WN7mnjet6NZ1Kc7aQ5wQpI9fvGDFXlUTz3W9PTx9qSDcL4ipvk7HE2Nw94A6Wf8nbukMUhUb9LkKkTRYmvyvs; Path=/; HttpOnly, WASReqURL=""; Expires=Thu, 01 Dec 1994 16:00:00 GMT; Path=/; HttpOnly', 'Expires': 'Thu, 01 Dec 1994 16:00:00 GMT', 'Location': 'http://rtc/ccm/authenticated/identity', 'Cache-Control': 'no-cache="set-cookie, set-cookie2"', 'Date': 'Wed, 07 Jun 2017 15:13:10 GMT'}

Can this be fixed please?

**Comment by dixudx** [comment]
Have you changed something? Would you kindly paste your code and detailed logs ?

**Comment by dixudx** [comment]
@Feva Actually `authfailed` is handled when logging in. Refer to [client.py#L107-L111](https://github.com/dixudx/rtcclient/blob/development/rtcclient/client.py#L107-L111).

I guess in rtc *6.0.3*, the header has been changed for bad login. Would you please help log the content of `resp.headers` in [client.py#L108](https://github.com/dixudx/rtcclient/blob/development/rtcclient/client.py#L107-L111) or submit a pull request for your convenience.

Thanks.

**Comment by Feva** [comment]
@dixudx 

I included the headers for good and bad in the original issue.

I have been testing with a hard coded test account. Now I was looking at creating a login prompt so tested with bad data. I did not receive an exception as expected.

As you can see from my original issue the good and bad login does not contain the "x-com-ibm-team-repository-web-auth-msg" that you are testing for.

Do you need me to do anything else?

**Comment by dixudx** [comment]
Now that the only solution to differentiate these two headers is the attribute `Location`. If the `Location` ends up with **authfailed**, then an exception on bad login should be raised.

I was thinking if we could fetch more precise information on this, just as the old one **x-com-ibm-team-repository-web-auth-msg**.

@Feva Was that all in the headers of bad logging?

**Comment by Feva** [comment]
@dixudx 
Yes.

Please look at: https://gist.github.com/Feva/bc6203d5c0db0ad68be1894eb66b6c01

**Comment by dixudx** [comment]
@Feva Thanks so much for your information. Try [this bug fix](https://github.com/dixudx/rtcclient/commit/58247303645d8abe491eba043ab0be2e823a6e6b).

**Comment by Feva** [comment]
@dixudx 
That worked thank you.
