### ISSUE TITLE
XMLSyntaxError when trying to use '<' or '>' in WorkItem title or description

### ISSUE THREAD

**Issue by Mershl** [dixudx/rtcclient#96]
Using `<` or `>` in a title or description string of a new workitem will result in 
```
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch
```
Tested on development branch.

**Comment by dixudx** [comment]
@Mershl Yeah exactly. `<` is not escaped. My fault.

**Comment by dixudx** [comment]
@Mershl Already fixed. Sorry for the inconveniences.
